### ISSUE TITLE
ebitenmobile bind error ... no type or protocol named 'EbitenmobileviewRenderRequester'

### ISSUE THREAD

**Issue by peterSZW** [yohamta/godanmaku#1]
When I use the cmd below , it does not work on godanmaku but this cmd works on go-inovation.

~/go/bin/ebitenmobile bind -target ios -o ./mobile/ios/Mobile.framework ./mobile

gomobile: ios-arm64: go build -buildmode=c-archive -o /var/folders/tg/fwjc45r90cz33vmvsvjp1zg00000gp/T/gomobile-work-2554193494/Mobile-arm64.a ./gobind failed: exit status 2
# golang.org/x/mobile/app
darwin_ios.m:139:77: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
# gobind/gobind
mobileebitenviewcontroller_ios.m:20:58: error: no type or protocol named 'EbitenmobileviewRenderRequester'
mobileebitenviewcontroller_ios.m:74:3: error: implicit declaration of function 'EbitenmobileviewSetRenderRequester' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
mobileebitenviewcontroller_ios.m:179:29: error: too many arguments to function call, expected 0, have 1
gobind/Ebitenmobileview.objc.h:27:24: note: 'EbitenmobileviewSuspend' declared here
mobileebitenviewcontroller_ios.m:192:28: error: too many arguments to function call, expected 0, have 1
gobind/Ebitenmobileview.objc.h:20:24: note: 'EbitenmobileviewResume' declared here

**Comment by peterSZW** [comment]
Change go.mod  file :	
github.com/hajimehoshi/ebiten/v2 v2.2.0-alpha.15

Ebitenmobile bind success.

But when run this game in iOS , the touch grid does not work. :-(

**Comment by yohamta0** [comment]
@peterSZW Hi, thank you for raising the issue. I just fixed the issue of the touch grid.
For the issue of ios build, I faced the same problem but it is fixed after I run this command `go install github.com/hajimehoshi/ebiten/v2/cmd/ebitenmobile@latest`. Could you please confirm if it is fixed on your end as well.

**Comment by peterSZW** [comment]
It works great on my iphone 11 ~ [thumbs-up]

**Comment by yohamta0** [comment]
Glad to hear that!
